/*
 * Hello World Service
 *
 * Hello World service with support for multiple languages.
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// ItemsApiRouter defines the required methods for binding the api requests to a responses for the ItemsApi
// The ItemsApiRouter implementation should parse necessary information from the http request, 
// pass the data to a ItemsApiServicer to perform the required actions, then write the service results to the http response.
type ItemsApiRouter interface { 
	CreateItem(http.ResponseWriter, *http.Request)
	DeleteItem(http.ResponseWriter, *http.Request)
	GetItem(http.ResponseWriter, *http.Request)
	GetItems(http.ResponseWriter, *http.Request)
	UpdateItem(http.ResponseWriter, *http.Request)
}
// LanguagesApiRouter defines the required methods for binding the api requests to a responses for the LanguagesApi
// The LanguagesApiRouter implementation should parse necessary information from the http request, 
// pass the data to a LanguagesApiServicer to perform the required actions, then write the service results to the http response.
type LanguagesApiRouter interface { 
	CreateLanguage(http.ResponseWriter, *http.Request)
	DeleteLanguage(http.ResponseWriter, *http.Request)
	GetLanguage(http.ResponseWriter, *http.Request)
	GetLanguages(http.ResponseWriter, *http.Request)
	UpdateLanguage(http.ResponseWriter, *http.Request)
}


// ItemsApiServicer defines the api actions for the ItemsApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type ItemsApiServicer interface { 
	CreateItem(context.Context, Item) (ImplResponse, error)
	DeleteItem(context.Context, string) (ImplResponse, error)
	GetItem(context.Context, string) (ImplResponse, error)
	GetItems(context.Context, string) (ImplResponse, error)
	UpdateItem(context.Context, string, Item) (ImplResponse, error)
}


// LanguagesApiServicer defines the api actions for the LanguagesApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type LanguagesApiServicer interface { 
	CreateLanguage(context.Context, Language) (ImplResponse, error)
	DeleteLanguage(context.Context, string) (ImplResponse, error)
	GetLanguage(context.Context, string) (ImplResponse, error)
	GetLanguages(context.Context) (ImplResponse, error)
	UpdateLanguage(context.Context, string, Language) (ImplResponse, error)
}
