/*
 * Hello World Service
 *
 * Hello World service with support for multiple languages.
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"log"
	"net/http"
	"errors"
)

// StubItem is a sample item for this simple implementation
var StubItem = Item{
	Id:           "a619249d-8d5a-4b40-8b1f-ba4da2f8199b",
	LanguageId:   "20f329ac-123f-48f0-917d-a70497cfd22a",
	LanguageName: "Esperanto",
	Value:        "Saluton mondo",
}

// ItemsApiService is a service that implents the logic for the ItemsApiServicer
// This service should implement the business logic for every endpoint for the ItemsApi API. 
// Include any external packages or services that will be required by this service.
type ItemsApiService struct {
}

// NewItemsApiService creates a default api service
func NewItemsApiService() ItemsApiServicer {
	return &ItemsApiService{}
}

// CreateItem - Creates a new Hello World item.
func (s *ItemsApiService) CreateItem(ctx context.Context, item Item) (ImplResponse, error) {
	log.Printf("Hello World - Create Item")

	// TODO - update CreateItem with the required logic for this service method.
	// Add api_items_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, Item{}) or use other options such as http.Ok ...
	//return Response(201, Item{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	//return Response(403, Error{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateItem method not implemented")
}

// DeleteItem - Deletes a Hello World item.
func (s *ItemsApiService) DeleteItem(ctx context.Context, id string) (ImplResponse, error) {
	log.Printf("Hello World - Delete Item")

	// TODO - update DeleteItem with the required logic for this service method.
	// Add api_items_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	//return Response(403, Error{}), nil

	//TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	//return Response(404, Error{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteItem method not implemented")
}

// GetItem - Returns a Hello World item.
func (s *ItemsApiService) GetItem(ctx context.Context, id string) (ImplResponse, error) {
	log.Printf("Hello World - Get Item")

	// TODO - update GetItem with the required logic for this service method.
	// Add api_items_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Item{}) or use other options such as http.Ok ...
	//return Response(200, Item{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	//return Response(403, Error{}), nil

	//TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	//return Response(404, Error{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusOK, StubItem), nil
}

// GetItems - Returns a list of Hello World items.
func (s *ItemsApiService) GetItems(ctx context.Context, languageId string) (ImplResponse, error) {
	log.Printf("Hello World - Get Items")

	// TODO - update GetItems with the required logic for this service method.
	// Add api_items_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Item{}) or use other options such as http.Ok ...
	//return Response(200, []Item{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	//return Response(403, Error{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	list := []Item{StubItem}
	return Response(http.StatusOK, list), nil
}

// UpdateItem - Updates a Hello World item.
func (s *ItemsApiService) UpdateItem(ctx context.Context, id string, item Item) (ImplResponse, error) {
	log.Printf("Hello World - Update Item")

	// TODO - update UpdateItem with the required logic for this service method.
	// Add api_items_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Item{}) or use other options such as http.Ok ...
	//return Response(200, Item{}), nil

	//TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	//return Response(400, Error{}), nil

	//TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	//return Response(401, Error{}), nil

	//TODO: Uncomment the next line to return response Response(403, Error{}) or use other options such as http.Ok ...
	//return Response(403, Error{}), nil

	//TODO: Uncomment the next line to return response Response(404, Error{}) or use other options such as http.Ok ...
	//return Response(404, Error{}), nil

	//TODO: Uncomment the next line to return response Response(500, Error{}) or use other options such as http.Ok ...
	//return Response(500, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateItem method not implemented")
}

