#
# Copyright (c) 2021 Cisco Systems, Inc and its affiliates
# All rights reserved
#

# Invoke: 
# nmake /F Makefile.win NAME=slminitproofservice VERSION=1.0.0

GO111MODULE=on

IMAGE = ..\go-hello-world-service-8\$(NAME)-$(VERSION).tar.gz

build: clean package

package:
	docker build -t $(NAME):$(VERSION) .
	docker save $(NAME):$(VERSION) | gzip > $(IMAGE)

clean:
	del /F $(IMAGE)

