/*
 * Hello World Service
 *
 * Hello World service with support for multiple languages.
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Item struct {
	Id           string `json:"id,omitempty"`
	LanguageId   string `json:"languageId"`
	LanguageName string `json:"languageName,omitempty"`
	Value        string `json:"value"`
}
