/*
 * Hello World Service
 *
 * Hello World service with support for multiple languages.
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Language struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`
}
